import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'
import torch from '../../public/torch.svg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid background grid-rows-8 grid-cols-1 w-screen h-screen`}>
        <header className='flex w-full h-full px-8 items-center justify-between col-span-1 row-start-1 row-end-1'>
          <svg fill="#000000" height="4em" width="4em">
            <g>
              <g>
                <path d="M423.923,298.804L248.665,123.546c-8.007-8.008-20.991-8.008-29,0l-50.314,50.313c-8.003,8.004-8.007,20.993,0,29
			l23.768,23.767c-5.394,7.038-148.87,194.212-154.26,201.242c-6.258,8.164-5.498,19.701,1.774,26.975l51.152,51.152
			c7.255,7.255,18.747,8.026,26.904,1.829c7.039-5.347,195.033-148.164,202.096-153.529l23.823,23.823
			c8.008,8.008,20.992,8.008,29,0l50.314-50.313C431.926,319.801,431.93,306.811,423.923,298.804z M108.131,464.339l-25.787-25.787
			l71.62-93.434l47.964,47.965L108.131,464.339z M234.889,368.043l-55.758-55.758l43.239-56.408l69.145,69.145L234.889,368.043z
			 M359.108,334.616L212.852,188.359l21.313-21.313l146.257,146.257L359.108,334.616z"/>
              </g>
            </g>
            <g>
              <g>
                <path d="M442.566,3.503c-48.065-20.713-112.677,55.741-127.435,89.993c-17.806,41.328,1.225,89.189,42.56,106.998
			c41.333,17.806,89.191-1.228,106.998-42.56C479.443,123.694,490.642,24.217,442.566,3.503z M427.023,141.706
			c-8.837,20.512-32.588,29.962-53.105,21.123c-20.514-8.838-29.962-32.59-21.123-53.104c5.046-11.713,19.901-32.333,38.528-49.083
			c17.084-15.362,28.997-19.704,33.554-19.704c0.629,0,1.117,0.082,1.46,0.23c2.828,1.219,9.248,12.686,9.896,38.824
			C436.854,105.034,432.071,129.993,427.023,141.706z"/>
              </g>
            </g>
            <g>
              <g>
                <circle cx="389.384" cy="126.932" r="21.19" />
              </g>
            </g>
          </svg>
          <nav>
            <Link href={`/`} className='text'>Home</Link>
            <Link href={`/signup`} className='text ml-4'>Sign Up</Link>
            <Link href={`/login`} className='text ml-4'>Log In</Link>
          </nav>
        </header>
        <main className='col-span-1 row-start-2 row-end-7'>
          {children}
        </main>
      </body>
    </html>
  )
}
